#!/bin/sh
#
# @name Holybro X500 V2
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Farhang Naderi <farhang.nba@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

# Multicopter default parameters. Copied and modified from 'rc.mc_defaults'
#
# NOTE: Script variables are declared/initialized/unset in the rcS script.
set VEHICLE_TYPE mc

param set-default IMU_GYRO_RATEMAX 800

param set-default NAV_ACC_RAD 2

param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10

param set-default PWM_MAIN_MAX 1950
param set-default PWM_MAIN_MIN 1075
param set-default PWM_MAIN_RATE 400

param set-default GPS_UBX_DYNMODEL 6

# set the Custom mixer configured to have payload deployment pin
set MIXER quad_x_payload_delivery

# We use 1 ~ 4 for Motor, 5 for Payload Deployment
set PWM_OUT 12345

# This is the gimbal pass mixer.
set MIXER_AUX pass

set PWM_AUX_OUT 1234

param set-default IMU_GYRO_CUTOFF 30

param set-default MC_ROLLRATE_P 0.14
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCHRATE_D 0.004

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.25
param set-default CA_ROTOR0_PY 0.25
param set-default CA_ROTOR1_PX -0.25
param set-default CA_ROTOR1_PY -0.25
param set-default CA_ROTOR2_PX 0.25
param set-default CA_ROTOR2_PY -0.25
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.25
param set-default CA_ROTOR3_PY 0.25
param set-default CA_ROTOR3_KM -0.05
